version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./config/ServersToLoad.json:/pgadmin4/servers.json
      - ./config/PreferencesToSet.json:/pgadmin4/preferences.json
      
volumes:
  pgadmin-data:
    name: 'pgadmin-data'